### ISSUE TITLE
backend architecture

### ISSUE THREAD

**Issue by dzfranklin** [dzfranklin/plantopo#54]
we could use kubernetes leases to elect a leader. how do we sync a new leader with each client though? after coming up but before it's ready the new leader should try and connect to each follower. the followers kill all their sessions and ack the setup. client handlers discover the leader and ask it for a session. the leader then picks a follower at random and asks it to take the session (if that fails mark the follower as dead and error up to the app to retry).

split out matchmaker, session-frontend, and session-backend packages from server. should be pretty simple, shouldn't need to do auth. include a token in the map meta response in a currentUserPermission field

**Comment by danielzfranklin** [comment]
to simplify can we just elect a single leader that does all the matchmaking and session shit?

**Comment by danielzfranklin** [comment]
what if we don't need anything complex for now? I don't think we even need zero downtime deploys for the backend as long as it's short.

we deploy the API server via a normal do app.

we do blue/green deploys of a single sync server. no locking, but our deploy tool ensures only one is live.

**Comment by danielzfranklin** [comment]
making this distributed prematurely is a mistake. see if we can find a way to do deploys without. maybe write go code against do api

**Comment by danielzfranklin** [comment]
maybe the API servers manage it? they could take a lock in postgres to rollback

**Comment by danielzfranklin** [comment]
maybe the API servers manage it? they could take a lock in postgres to rollback

or we could use dokku

**Comment by danielzfranklin** [comment]
what if we deploy a single stateful instance of the sync server, but have a clean way to failover to a secondary we can also use for deployment.

**Comment by danielzfranklin** [comment]
see <https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes>

**Comment by danielzfranklin** [comment]
why don't we have a single simple manually deployed and managed matchmaker. that matchmaker just exposes a single API that assigns you to a server. this is nice because the matchmaker then has a good perspective on what all the session backend health as it rpcs them before assigning and can have a health map

**Comment by danielzfranklin** [comment]
the session frontend servers (maybe the same as the API servers) talk to the matchmaker and then the session backend. so we don't have to expose service discovery to the outside world
