### ISSUE TITLE
map sync

### ISSUE THREAD

**Issue by dzfranklin** [dzfranklin/plantopo#6]
Handle acks in some way.

Don't overwrite changes locally with a broadcast if they haven't been acked yet.

**Comment by danielzfranklin** [comment]
maybe have WorkingChangeset store seq and handle removing everything covered by ack

**Comment by danielzfranklin** [comment]
the problem with stale data is that the update interval is racing against the user's local changes. We should prioritize local changes until they are acked, maybe?

**Comment by danielzfranklin** [comment]
could store seq intrusively in the store and just recursively walk to build deltas.

the only other data we'd need is the delete list

**Comment by dzfranklin** [comment]
Fixed by #97
